# Generated by Django 4.2.5 on 2023-09-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_lesson_url_lesson_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=150, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=150, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='пользователь'),
        ),
    ]
