# Generated by Django 4.2.5 on 2023-09-29 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_course_title_alter_lesson_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.date(2023, 9, 29), verbose_name='дата оплаты'),
        ),
    ]
