# Generated by Django 4.2.5 on 2023-10-02 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.date(2023, 10, 2), verbose_name='дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'наличные'), ('transfer', 'перевод')], default='перевод', max_length=15, verbose_name='способ оплаты'),
        ),
    ]
