# Generated by Django 4.2.5 on 2023-10-03 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 3, 11, 42, 19, 369646, tzinfo=datetime.timezone.utc), verbose_name='дата оплаты'),
        ),
    ]
